version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=some_random_secret_key

  test:
    build: .
    command: pytest
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=testing
      - SECRET_KEY=test_secret_key